# Generated by Django 3.1.3 on 2020-11-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arvores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('idade', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='GrupoArvores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('arvores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.arvores')),
            ],
        ),
        migrations.CreateModel(
            name='colheita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.CharField(max_length=255, verbose_name='Informações')),
                ('data_colheita', models.DateField()),
                ('peso_bruto', models.PositiveIntegerField()),
                ('arvore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.arvores')),
            ],
        ),
        migrations.AddField(
            model_name='arvores',
            name='especies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especies'),
        ),
    ]
