# Generated by Django 3.1.3 on 2020-11-04 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arvores',
            options={'verbose_name': 'Árvore', 'verbose_name_plural': 'Árvores'},
        ),
        migrations.AlterModelOptions(
            name='especies',
            options={'verbose_name': 'Espécie', 'verbose_name_plural': 'Espécies'},
        ),
        migrations.AlterModelOptions(
            name='grupoarvores',
            options={'verbose_name': 'Grupo de Árvores', 'verbose_name_plural': 'Grupo de Árvores'},
        ),
        migrations.AddField(
            model_name='colheita',
            name='grupo_arvores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grupoarvores'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='arvore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.arvores'),
        ),
    ]
