# Generated by Django 3.1.3 on 2020-11-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201104_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='grupo_arvores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GrupoArvores', to='api.grupoarvores'),
        ),
    ]
