# Generated by Django 3.1.3 on 2020-11-04 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201104_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='arvore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arvore', to='api.arvores', verbose_name='Árvores'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='data_colheita',
            field=models.DateField(verbose_name='Data da Colheita'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='grupo_arvores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_arvores', to='api.grupoarvores', verbose_name='Grupo de Árvores'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
