# Generated by Django 3.1.3 on 2020-11-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='arvore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.arvores', verbose_name='Árvores'),
        ),
        migrations.AlterField(
            model_name='colheita',
            name='grupo_arvores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.grupoarvores', verbose_name='Grupo de Árvores'),
        ),
    ]
