# Generated by Django 3.1.3 on 2020-11-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201104_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colheita',
            name='grupo_arvores',
        ),
        migrations.AddField(
            model_name='colheita',
            name='grupo_arvores',
            field=models.ManyToManyField(blank=True, to='api.GrupoArvores'),
        ),
    ]
