# Generated by Django 3.1.3 on 2020-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201104_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupoarvores',
            name='arvores',
        ),
        migrations.AddField(
            model_name='grupoarvores',
            name='arvores',
            field=models.ManyToManyField(to='api.Arvores'),
        ),
    ]
