# Generated by Django 3.1.3 on 2020-11-05 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201104_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='especie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.especies'),
        ),
    ]
