# Generated by Django 3.1.3 on 2020-11-05 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_colheita_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='especie',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.especies'),
        ),
    ]
