# Generated by Django 3.1.3 on 2020-11-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201105_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colheita',
            old_name='especie',
            new_name='especies',
        ),
    ]
