# Generated by Django 3.1.3 on 2020-11-05 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20201105_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colheita',
            name='especies',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.especies'),
        ),
    ]
